#!/usr/bin/env bash
# Runs inside the Voxmox LXC to install Node.js, the app, and systemd.
set -euo pipefail

APP_DIR="${APP_DIR:-/opt/voxmox}"
APP_USER="${APP_USER:-voxmox}"
APP_PORT="${APP_PORT:-43127}"
NODE_MAJOR="${NODE_MAJOR:-22}"
GIT_URL="${GIT_URL:-https://github.com/tr0lls3c/voxmox.git}"
GIT_BRANCH="${GIT_BRANCH:-main}"
USE_EXISTING_APP_DIR="${USE_EXISTING_APP_DIR:-0}"
PROXMOX_HOST_URL="${PROXMOX_HOST_URL:-}"
PROXMOX_TOKEN_ID="${PROXMOX_TOKEN_ID:-}"
PROXMOX_TOKEN_SECRET="${PROXMOX_TOKEN_SECRET:-}"
PROXMOX_MOCK="${PROXMOX_MOCK:-false}"
ALEXA_SKILL_ID="${ALEXA_SKILL_ID:-}"
SKIP_BUILD="${SKIP_BUILD:-0}"

export DEBIAN_FRONTEND=noninteractive

msg() { echo -e "[voxmox-install] $*"; }

wait_for_network() {
  for _ in $(seq 1 60); do
    if getent hosts deb.debian.org >/dev/null 2>&1 || ping -c1 -W1 1.1.1.1 >/dev/null 2>&1; then
      return 0
    fi
    sleep 1
  done
  msg "WARNING: network may not be ready; continuing anyway"
}

install_base_packages() {
  msg "Updating apt and installing base packages"
  apt-get update -y
  apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    gnupg \
    git \
    jq \
    ca-certificates \
    openssl \
    python3 \
    build-essential \
    locales
  sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen 2>/dev/null || true
  locale-gen en_US.UTF-8 >/dev/null 2>&1 || true
}

install_nodejs() {
  if command -v node >/dev/null 2>&1; then
    local major
    major="$(node -v | sed -E 's/^v([0-9]+).*/\1/')"
    if [[ "$major" -ge "$NODE_MAJOR" ]]; then
      msg "Node.js $(node -v) already installed"
      return
    fi
  fi

  msg "Installing Node.js ${NODE_MAJOR}.x"
  curl -fsSL "https://deb.nodesource.com/setup_${NODE_MAJOR}.x" | bash -
  apt-get install -y nodejs
  msg "Node $(node -v) / npm $(npm -v)"
}

create_app_user() {
  if ! id "$APP_USER" >/dev/null 2>&1; then
    useradd --system --home-dir "$APP_DIR" --shell /usr/sbin/nologin "$APP_USER"
  fi
  mkdir -p "$APP_DIR"
  chown -R "$APP_USER:$APP_USER" "$APP_DIR"
}

fetch_app() {
  if [[ "$USE_EXISTING_APP_DIR" == "1" && -f "$APP_DIR/package.json" ]]; then
    msg "Using application files already present in ${APP_DIR}"
    return
  fi

  msg "Cloning ${GIT_URL} (branch ${GIT_BRANCH})"
  rm -rf "${APP_DIR}.git-tmp"
  # Do not leak credentials into on-disk remote URL after clone.
  git clone --depth 1 --branch "$GIT_BRANCH" "$GIT_URL" "${APP_DIR}.git-tmp"
  rm -rf "${APP_DIR}.git-tmp/.git"
  find "$APP_DIR" -mindepth 1 -maxdepth 1 ! -name '.env' ! -name 'data' -exec rm -rf {} +
  shopt -s dotglob
  mv "${APP_DIR}.git-tmp"/* "$APP_DIR"/
  shopt -u dotglob
  rm -rf "${APP_DIR}.git-tmp"
  mkdir -p "$APP_DIR/data"
}

write_env() {
  local env_file="${APP_DIR}/.env"
  local mock="$PROXMOX_MOCK"
  if [[ -z "$PROXMOX_TOKEN_ID" || -z "$PROXMOX_TOKEN_SECRET" ]]; then
    mock="true"
  fi

  msg "Writing ${env_file}"
  cat >"$env_file" <<EOF
# Generated by Voxmox LXC installer
PROXMOX_HOST=${PROXMOX_HOST_URL}
PROXMOX_TOKEN_ID=${PROXMOX_TOKEN_ID}
PROXMOX_TOKEN_SECRET=${PROXMOX_TOKEN_SECRET}
PROXMOX_MOCK=${mock}
PROXMOX_ALLOW_SELF_SIGNED=true
NODE_TLS_REJECT_UNAUTHORIZED=0
ALEXA_SKILL_ID=${ALEXA_SKILL_ID}
ALEXA_SKIP_SIGNATURE_VALIDATION=false
PORT=${APP_PORT}
VOXMOX_DATA_DIR=${APP_DIR}/data
EOF
  chmod 640 "$env_file"
  chown "$APP_USER:$APP_USER" "$env_file"
  mkdir -p "${APP_DIR}/data"
  chown -R "$APP_USER:$APP_USER" "${APP_DIR}/data"
}

build_app() {
  if [[ "$SKIP_BUILD" == "1" ]]; then
    msg "SKIP_BUILD=1 — skipping npm install/build"
    return
  fi
  msg "Installing npm dependencies and building Next.js app"
  cd "$APP_DIR"
  # Ensure package-lock installs reproducibly when present.
  if [[ -f package-lock.json ]]; then
    runuser -u "$APP_USER" -- npm ci
  else
    runuser -u "$APP_USER" -- npm install
  fi
  runuser -u "$APP_USER" -- npm run build
}

install_systemd() {
  msg "Installing systemd unit"
  if [[ -f /tmp/voxmox.service ]]; then
    cp /tmp/voxmox.service /etc/systemd/system/voxmox.service
  else
    cat >/etc/systemd/system/voxmox.service <<EOF
[Unit]
Description=Voxmox Alexa + Proxmox dashboard
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${APP_USER}
Group=${APP_USER}
WorkingDirectory=${APP_DIR}
Environment=NODE_ENV=production
Environment=PORT=${APP_PORT}
EnvironmentFile=-${APP_DIR}/.env
ExecStart=${APP_DIR}/node_modules/.bin/next start -H 0.0.0.0 -p ${APP_PORT}
Restart=on-failure
RestartSec=3
TimeoutStartSec=30

[Install]
WantedBy=multi-user.target
EOF
  fi

  # Substitute placeholders if the unit file uses them
  sed -i \
    -e "s|__APP_DIR__|${APP_DIR}|g" \
    -e "s|__APP_USER__|${APP_USER}|g" \
    -e "s|__APP_PORT__|${APP_PORT}|g" \
    /etc/systemd/system/voxmox.service

  systemctl daemon-reload
  systemctl enable --now voxmox.service
}

install_update_helper() {
  msg "Installing /usr/bin/update (community-scripts style)"
  apt-get install -y --no-install-recommends rsync >/dev/null

  mkdir -p /etc/voxmox
  # Persist clone URL from install so plain `update` works later.
  # For public GitHub this is just https://github.com/… with no token.
  # For private GitHub you may embed a PAT: https://ghp_…@github.com/….git
  cat >/etc/voxmox/update.conf <<EOF
# Voxmox update configuration (chmod 600)
GIT_URL='${GIT_URL}'
GIT_BRANCH='${GIT_BRANCH}'
APP_DIR='${APP_DIR}'
APP_USER='${APP_USER}'
NODE_MAJOR='${NODE_MAJOR}'
EOF
  chmod 600 /etc/voxmox/update.conf

  if [[ -f /tmp/voxmox-update.sh ]]; then
    cp /tmp/voxmox-update.sh /usr/bin/update
  else
    msg "WARNING: /tmp/voxmox-update.sh missing — writing embedded updater"
    # Fallback should not normally run; host script pushes the canonical updater.
    cat >/usr/bin/update <<'EOF'
#!/usr/bin/env bash
echo "Voxmox updater missing. Re-run the LXC installer or copy scripts/lxc/update to /usr/bin/update."
exit 1
EOF
  fi
  chmod 755 /usr/bin/update

  # Friendly aliases used in docs / muscle memory
  ln -sfn /usr/bin/update /usr/local/bin/update
  ln -sfn /usr/bin/update /usr/local/bin/voxmox-update
}

configure_motd() {
  cat >/etc/motd <<EOF

  Voxmox LXC
  -------------
  Dashboard : http://$(hostname -I | awk '{print $1}'):${APP_PORT}
  Alexa     : /api/alexa
  App dir   : ${APP_DIR}
  Service   : systemctl status voxmox
  Update    : update

EOF
}

main() {
  wait_for_network
  install_base_packages
  install_nodejs
  create_app_user
  fetch_app
  chown -R "$APP_USER:$APP_USER" "$APP_DIR"
  write_env
  build_app
  install_systemd
  install_update_helper
  configure_motd

  # Brief readiness check
  sleep 2
  if systemctl is-active --quiet voxmox; then
    msg "voxmox.service is active"
  else
    msg "WARNING: voxmox.service is not active yet — check: journalctl -u voxmox -n 100"
    systemctl --no-pager --full status voxmox || true
  fi
  msg "Install finished"
}

main "$@"
